[package]
name = "bb_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
dynomite = { version = "0.10.0", default_features = false, features = ["rustls"] }
env_logger = "0.9"
flate2 = "1"
rusoto_core = { version = "0.47.0", default_features = false, features=["rustls"] }
rusoto_dynamodbstreams = { version = "0.47.0", default_features = false, features=["rustls", "serialize_structs"] }
rusoto_lambda = { version = "0.47.0", default_features = false, features=["rustls", "serialize_structs"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
thiserror = "1"