[package]
name = "bb_rust"
version = "0.1.0"
edition = "2021"

[[example]]
name = "gateway_graphql_request"
required-features = ["graphql"]

[dependencies]
base64 = {version = "0.13", optional = true }
aws-sdk-lambda = { version = "0.6", optional = true }
dynomite = { git = "https://github.com/softprops/dynomite.git", rev = "4669592b83750ef7d6f40265c729ed059e86b119", default_features = false, features=["rustls"], optional = true }
env_logger = {version = "0.9", optional = true }
flate2 = { version = "1", optional = true }
log = {version = "0.4", optional = true}
rusoto_dynamodbstreams = { version = "0.47.0", default_features = false, features=["rustls", "serialize_structs"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = { version = "1", optional = true }
lazy_static = "1.4.0"

[dev-dependencies]
tokio = {version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
aws-config = "0.6"
cargo-husky = { version = "1.5.0", default_features = false, features = ["precommit-hook", "run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"] }

[features]
default = []
dynamodb = ["dynomite", "rusoto_dynamodbstreams"]
misc = ["thiserror", "flate2", "base64", "env_logger", "log"]
graphql = ["misc", "base64", "aws-sdk-lambda"]
